# Generated by Django 5.0.3 on 2024-10-16 18:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('profileimg', models.ImageField(upload_to='profile_img')),
                ('bio', models.TextField(blank=True)),
                ('accentcolor', models.CharField(default='#75D8A2', max_length=7, validators=[django.core.validators.RegexValidator(regex='^#[0-9A-Fa-f]{6}$')])),
                ('bgcolor', models.CharField(default='#141414', max_length=7, validators=[django.core.validators.RegexValidator(regex='^#[0-9A-Fa-f]{6}$')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
